### ISSUE TITLE
Having a Tag other than retry against a scenario causes a duplicate attribute error

### ISSUE THREAD

**Issue by andydavidsmith** [farum12/NUnitRetry.SpecFlowPlugin#1]
If you have a scenario with a tag other than retry you end up with following error

Error	CS0579	Duplicate 'NUnit.Framework.Retry' attribute	

@AnotherTag
Scenario: OtherTags can be used
	When I increment the default retry count
	Then the retry result should be 5

@AnotherDifferentTag
Scenario outline: OtherTags can be used
	When I increment the default retry count
	Then the retry result should be <result>

Examples:
|result|
|5|

**Comment by farum12** [comment]
Thanks! I will look into that.

**Comment by farum12** [comment]
Confirmed. Adding other tag than (@)Retry causes Error CS0579 Duplicate 'NUnit.Framework.Retry' attribute.
Current walkaround until fix: set applyGlobally flag onto false.

**Comment by farum12** [comment]
I've published the version with a fix - https://www.nuget.org/packages/NUnitRetry.SpecFlowPlugin/3.9.59
Please let me know @andydavidsmith if that resolved the issue on your side.
